Repository skypjack/entt, pull requests merged in 2019-08, with the labels that each got.

#290 benchmark to use entt::component
  AUTHORS
  test/benchmark/benchmark.cpp
Labels: triage

#291 Bazel Support (#287)
  .gitignore
  BUILD.bazel
  WORKSPACE
  bazel/BUILD.bazel
  bazel/copts.bzl
  test/BUILD.bazel
  test/benchmark/BUILD.bazel
  test/entt/BUILD.bazel
  test/entt/core/BUILD.bazel
  test/entt/entity/BUILD.bazel
  test/entt/locator/BUILD.bazel
  test/entt/meta/BUILD.bazel
  test/entt/process/BUILD.bazel
  test/entt/resource/BUILD.bazel
  test/entt/signal/BUILD.bazel
  test/lib/BUILD.bazel
  test/mod/BUILD.bazel
  test/snapshot/BUILD.bazel
Labels: build system

#285 Prototype of LSD radix sorting algorithm and an example of working wi…
  src/entt/core/algorithm.hpp
  test/entt/core/algorithm.cpp
Labels: feature request

#302 Update AUTHORS
  AUTHORS
Labels: documentation
