Repository skypjack/entt, pull requests merged in 2019-09, with the labels that each got.

#309 Mark CMake project explicitly as C++
  CMakeLists.txt
Labels: enhancement

#310 Use Ninja on AppVeyor
  appveyor.yml
Labels: build system

#319 Fix entt::collector.where
  src/entt/entity/observer.hpp
  test/entt/entity/observer.cpp
Labels: bug

#322 Add namespace qualifier in CMake (close #321)
  CMakeLists.txt
Labels: build system

#325 This should allow any type to be used as Delta...
  src/entt/process/process.hpp
Labels: enhancement
